name: name1

on:
  schedule:
    - cron: "0/5 * * * *"
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-python@latest
      - run: python main.py > output.txt
