name: name1

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
      - name: Set git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - run: |
          python main.py > output
          git add .
          git commit -m "Update output"
          git push origin main
